var qbData = [
{'quarterback': 'Tom Brady', 'team': 'NEP', 'home_away': 'vs.', 'opponent': 'MIA', 'adjPF': '22.0', 'adjPA': '21.1', 'Proj': '22.5'},
{'quarterback': 'Russell Wilson', 'team': 'SEA', 'home_away': '@', 'opponent': 'SFF', 'adjPF': '22.5', 'adjPA': '18.8', 'Proj': '21.4'},
{'quarterback': 'Kirk Cousins', 'team': 'WAS', 'home_away': 'vs.', 'opponent': 'NYG', 'adjPF': '22.0', 'adjPA': '19.7', 'Proj': '20.8'},
{'quarterback': 'Carson Wentz', 'team': 'PHI', 'home_away': 'vs.', 'opponent': 'CHI', 'adjPF': '21.5', 'adjPA': '15.1', 'Proj': '20.5'},
{'quarterback': 'Cam Newton', 'team': 'CAR', 'home_away': '@', 'opponent': 'NYJ', 'adjPF': '20.0', 'adjPA': '22.1', 'Proj': '20.4'},
{'quarterback': 'Alex Smith', 'team': 'KCC', 'home_away': 'vs.', 'opponent': 'BUF', 'adjPF': '20.3', 'adjPA': '15.3', 'Proj': '19.9'},
{'quarterback': 'Matt Ryan', 'team': 'ATL', 'home_away': 'vs.', 'opponent': 'TBB', 'adjPF': '17.3', 'adjPA': '20.9', 'Proj': '19.7'},
{'quarterback': 'Ben Roethlisberger', 'team': 'PIT', 'home_away': 'vs.', 'opponent': 'GBP', 'adjPF': '17.6', 'adjPA': '18.1', 'Proj': '19.0'},
{'quarterback': 'Marcus Mariota', 'team': 'TEN', 'home_away': '@', 'opponent': 'IND', 'adjPF': '16.7', 'adjPA': '19.7', 'Proj': '18.9'},
{'quarterback': 'Andy Dalton', 'team': 'CIN', 'home_away': 'vs.', 'opponent': 'CLE', 'adjPF': '16.5', 'adjPA': '21.6', 'Proj': '18.8'},
{'quarterback': 'Jared Goff', 'team': 'LAR', 'home_away': 'vs.', 'opponent': 'NOS', 'adjPF': '17.6', 'adjPA': '16.8', 'Proj': '18.4'},
{'quarterback': 'Jacoby Brissett', 'team': 'IND', 'home_away': 'vs.', 'opponent': 'TEN', 'adjPF': '16.3', 'adjPA': '22.1', 'Proj': '18.2'},
{'quarterback': 'Philip Rivers', 'team': 'LAC', 'home_away': '@', 'opponent': 'DAL', 'adjPF': '17.1', 'adjPA': '18.7', 'Proj': '18.2'},
{'quarterback': 'Derek Carr', 'team': 'OAK', 'home_away': 'vs.', 'opponent': 'DEN', 'adjPF': '17.4', 'adjPA': '17.8', 'Proj': '17.9'},
{'quarterback': 'Matthew Stafford', 'team': 'DET', 'home_away': 'vs.', 'opponent': 'MIN', 'adjPF': '20.9', 'adjPA': '15.0', 'Proj': '17.9'},
{'quarterback': 'Tyrod Taylor', 'team': 'BUF', 'home_away': '@', 'opponent': 'KCC', 'adjPF': '18.5', 'adjPA': '17.9', 'Proj': '17.8'},
{'quarterback': 'Dak Prescott', 'team': 'DAL', 'home_away': 'vs.', 'opponent': 'LAC', 'adjPF': '19.4', 'adjPA': '15.5', 'Proj': '17.7'},
{'quarterback': 'Drew Brees', 'team': 'NOS', 'home_away': '@', 'opponent': 'LAR', 'adjPF': '19.5', 'adjPA': '14.3', 'Proj': '17.6'},
{'quarterback': 'Ryan Fitzpatrick', 'team': 'TBB', 'home_away': '@', 'opponent': 'ATL', 'adjPF': '18.5', 'adjPA': '18.1', 'Proj': '17.2'},
{'quarterback': 'Blake Bortles', 'team': 'JAC', 'home_away': '@', 'opponent': 'ARI', 'adjPF': '15.8', 'adjPA': '18.7', 'Proj': '16.8'},
{'quarterback': 'Case Keenum', 'team': 'MIN', 'home_away': '@', 'opponent': 'DET', 'adjPF': '15.8', 'adjPA': '17.7', 'Proj': '16.6'},
{'quarterback': 'Eli Manning', 'team': 'NYG', 'home_away': '@', 'opponent': 'WAS', 'adjPF': '16.1', 'adjPA': '18.2', 'Proj': '15.8'},
{'quarterback': 'Paxton Lynch', 'team': 'DEN', 'home_away': '@', 'opponent': 'OAK', 'adjPF': '13.7', 'adjPA': '21.2', 'Proj': '15.6'},
{'quarterback': 'C.J. Beathard', 'team': 'SFF', 'home_away': 'vs.', 'opponent': 'SEA', 'adjPF': '17.5', 'adjPA': '15.6', 'Proj': '15.5'},
{'quarterback': 'Joe Flacco', 'team': 'BAL', 'home_away': 'vs.', 'opponent': 'HOU', 'adjPF': '8.8', 'adjPA': '22.4', 'Proj': '15.3'},
{'quarterback': 'Josh McCown', 'team': 'NYJ', 'home_away': 'vs.', 'opponent': 'CAR', 'adjPF': '16.6', 'adjPA': '15.2', 'Proj': '15.3'},
{'quarterback': 'Jay Cutler', 'team': 'MIA', 'home_away': '@', 'opponent': 'NEP', 'adjPF': '14.7', 'adjPA': '20.5', 'Proj': '15.2'},
{'quarterback': 'DeShone Kizer', 'team': 'CLE', 'home_away': '@', 'opponent': 'CIN', 'adjPF': '13.1', 'adjPA': '17.7', 'Proj': '13.9'},
{'quarterback': 'Blaine Gabbert', 'team': 'ARI', 'home_away': 'vs.', 'opponent': 'JAC', 'adjPF': '18.2', 'adjPA': '10.1', 'Proj': '13.3'},
{'quarterback': 'Mitchell Trubisky', 'team': 'CHI', 'home_away': '@', 'opponent': 'PHI', 'adjPF': '10.9', 'adjPA': '15.9', 'Proj': '12.7'},
{'quarterback': 'Tom Savage', 'team': 'HOU', 'home_away': '@', 'opponent': 'BAL', 'adjPF': '11.9', 'adjPA': '12.9', 'Proj': '11.1'},
{'quarterback': 'Brett Hundley', 'team': 'GBP', 'home_away': '@', 'opponent': 'PIT', 'adjPF': '9.9', 'adjPA': '14.3', 'Proj': '11.1'}
];

var matchups = [
'Tom Brady (NEP vs. MIA): 22.5 proj. pts.', 
'Russell Wilson (SEA @ SFF): 21.4 proj. pts.', 
'Kirk Cousins (WAS vs. NYG): 20.8 proj. pts.', 
'Carson Wentz (PHI vs. CHI): 20.5 proj. pts.', 
'Cam Newton (CAR @ NYJ): 20.4 proj. pts.', 
'Alex Smith (KCC vs. BUF): 19.9 proj. pts.', 
'Matt Ryan (ATL vs. TBB): 19.7 proj. pts.', 
'Ben Roethlisberger (PIT vs. GBP): 19 proj. pts.', 
'Marcus Mariota (TEN @ IND): 18.9 proj. pts.', 
'Andy Dalton (CIN vs. CLE): 18.8 proj. pts.', 
'Jared Goff (LAR vs. NOS): 18.4 proj. pts.', 
'Jacoby Brissett (IND vs. TEN): 18.2 proj. pts.', 
'Philip Rivers (LAC @ DAL): 18.2 proj. pts.', 
'Derek Carr (OAK vs. DEN): 17.9 proj. pts.', 
'Matthew Stafford (DET vs. MIN): 17.9 proj. pts.', 
'Tyrod Taylor (BUF @ KCC): 17.8 proj. pts.', 
'Dak Prescott (DAL vs. LAC): 17.7 proj. pts.', 
'Drew Brees (NOS @ LAR): 17.6 proj. pts.', 
'Ryan Fitzpatrick (TBB @ ATL): 17.2 proj. pts.', 
'Blake Bortles (JAC @ ARI): 16.8 proj. pts.', 
'Case Keenum (MIN @ DET): 16.6 proj. pts.', 
'Eli Manning (NYG @ WAS): 15.8 proj. pts.', 
'Paxton Lynch (DEN @ OAK): 15.6 proj. pts.', 
'C.J. Beathard (SFF vs. SEA): 15.5 proj. pts.', 
'Joe Flacco (BAL vs. HOU): 15.3 proj. pts.', 
'Josh McCown (NYJ vs. CAR): 15.3 proj. pts.', 
'Jay Cutler (MIA @ NEP): 15.2 proj. pts.', 
'DeShone Kizer (CLE @ CIN): 13.9 proj. pts.', 
'Blaine Gabbert (ARI vs. JAC): 13.3 proj. pts.', 
'Mitchell Trubisky (CHI @ PHI): 12.7 proj. pts.', 
'Tom Savage (HOU @ BAL): 11.1 proj. pts.', 
'Brett Hundley (GBP @ PIT): 11.1 proj. pts.', 
]